name: aversan_pig_streaming
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.10+1
  flutter_launcher_icons: "^0.10.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.0

#########################################
flutter_native_splash:
  color: "#995C76" 
  color_dark: "#2B2725"
  image: assets/pig.png
#########################################

#########################################
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/launcher_icon.png
  adaptive_icon_foreground: assets/launcher_icon.png
  adaptive_icon_background: "#2B2725"
  background_color: "#2B2725"
  min_sdk_android: 21 # android min sdk min:16, default 21
#########################################


flutter:

  uses-material-design: true
  assets:
    - assets/icon1x.png
