name: CI

on:
  push:
    branches:
      - sviluppo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install packages
        run: flutter pub get

      - name: Build Android
        run: flutter build appbundle

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Set up environment variables
        env:
          ENV_FILE: .env
        run: |
          echo "ENV_FILE=$ENV_FILE" >> $GITHUB_ENV

      - name: Copy .env to build directory
        run: |
          cp $ENV_FILE build/app/outputs/flutter-apk/.env
          cp $ENV_FILE build/ios/Runner/.env
